// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramGroupsAdmin.Data;

#nullable disable

namespace TgSpam_PreFilterApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015001635_AddConfigsTable")]
    partial class AddConfigsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.AuditLogRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("text")
                        .HasColumnName("target_user_id");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ChatAdminRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCreator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_creator");

                    b.Property<long>("LastVerifiedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_verified_at");

                    b.Property<long>("PromotedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("promoted_at");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("TelegramId");

                    b.ToTable("chat_admins");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ChatPromptRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("text")
                        .HasColumnName("added_by");

                    b.Property<long>("AddedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("added_date");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<string>("CustomPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("custom_prompt");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.ToTable("chat_prompts");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ConfigRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("LogConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("log_config");

                    b.Property<string>("ModerationConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("moderation_config");

                    b.Property<string>("SpamDetectionConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("spam_detection_config");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WelcomeConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("welcome_config");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("configs");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.DetectionResultRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("text")
                        .HasColumnName("added_by");

                    b.Property<string>("CheckResultsJson")
                        .HasColumnType("text")
                        .HasColumnName("check_results_json");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("detected_at");

                    b.Property<string>("DetectionMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detection_method");

                    b.Property<string>("DetectionSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detection_source");

                    b.Property<int>("EditVersion")
                        .HasColumnType("integer")
                        .HasColumnName("edit_version");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_spam");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<int?>("NetConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("net_confidence");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<bool>("UsedForTraining")
                        .HasColumnType("boolean")
                        .HasColumnName("used_for_training");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("UsedForTraining");

                    b.ToTable("detection_results");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.InviteRecordDto", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<long?>("ModifiedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_at");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UsedBy")
                        .HasColumnType("character varying(450)")
                        .HasColumnName("used_by");

                    b.Property<string>("UserRecordDtoId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("Token");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UsedBy");

                    b.HasIndex("UserRecordDtoId");

                    b.ToTable("invites");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ManagedChatRecordDto", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatId"));

                    b.Property<long>("AddedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("added_at");

                    b.Property<int>("BotStatus")
                        .HasColumnType("integer")
                        .HasColumnName("bot_status");

                    b.Property<string>("ChatName")
                        .HasColumnType("text")
                        .HasColumnName("chat_name");

                    b.Property<int>("ChatType")
                        .HasColumnType("integer")
                        .HasColumnName("chat_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<long?>("LastSeenAt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("settings_json");

                    b.HasKey("ChatId");

                    b.ToTable("managed_chats");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.MessageEditRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EditDate")
                        .HasColumnType("bigint")
                        .HasColumnName("edit_date");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("NewContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("new_content_hash");

                    b.Property<string>("NewText")
                        .HasColumnType("text")
                        .HasColumnName("new_text");

                    b.Property<string>("OldContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("old_content_hash");

                    b.Property<string>("OldText")
                        .HasColumnType("text")
                        .HasColumnName("old_text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("message_edits");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.MessageRecordDto", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("ChatName")
                        .HasColumnType("text")
                        .HasColumnName("chat_name");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletionSource")
                        .HasColumnType("text")
                        .HasColumnName("deletion_source");

                    b.Property<long?>("EditDate")
                        .HasColumnType("bigint")
                        .HasColumnName("edit_date");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("PhotoFileId")
                        .HasColumnType("text")
                        .HasColumnName("photo_file_id");

                    b.Property<int?>("PhotoFileSize")
                        .HasColumnType("integer")
                        .HasColumnName("photo_file_size");

                    b.Property<string>("PhotoLocalPath")
                        .HasColumnType("text")
                        .HasColumnName("photo_local_path");

                    b.Property<string>("PhotoThumbnailPath")
                        .HasColumnType("text")
                        .HasColumnName("photo_thumbnail_path");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<string>("Urls")
                        .HasColumnType("text")
                        .HasColumnName("urls");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.RecoveryCodeRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("used_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("recovery_codes");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ReportDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionTaken")
                        .HasColumnType("text")
                        .HasColumnName("action_taken");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text")
                        .HasColumnName("admin_notes");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<int?>("ReportCommandMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("report_command_message_id");

                    b.Property<long>("ReportedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("reported_at");

                    b.Property<long?>("ReportedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("ReportedByUserName")
                        .HasColumnType("text")
                        .HasColumnName("reported_by_user_name");

                    b.Property<long?>("ReviewedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WebUserId")
                        .HasColumnType("character varying(450)")
                        .HasColumnName("web_user_id");

                    b.HasKey("Id");

                    b.HasIndex("WebUserId");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.SpamCheckConfigRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<string>("CheckName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("check_name");

                    b.Property<int?>("ConfidenceThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_threshold");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text")
                        .HasColumnName("configuration_json");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<long>("ModifiedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_date");

                    b.HasKey("Id");

                    b.ToTable("spam_check_configs");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.SpamDetectionConfigRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChatId")
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<long>("LastUpdated")
                        .HasColumnType("bigint")
                        .HasColumnName("last_updated");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("spam_detection_configs");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.StopWordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("text")
                        .HasColumnName("added_by");

                    b.Property<long>("AddedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("added_date");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("stop_words");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramLinkTokenRecordDto", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("used_at");

                    b.Property<long?>("UsedByTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("used_by_telegram_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserRecordDtoId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.HasIndex("UserRecordDtoId");

                    b.ToTable("telegram_link_tokens");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramUserMappingRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("LinkedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("linked_at");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("text")
                        .HasColumnName("telegram_username");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("telegram_user_mappings");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TrainingSampleDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("text")
                        .HasColumnName("added_by");

                    b.Property<long>("AddedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("added_date");

                    b.PrimitiveCollection<long[]>("ChatIds")
                        .HasColumnType("bigint[]")
                        .HasColumnName("chat_ids");

                    b.Property<int?>("ConfidenceWhenAdded")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_when_added");

                    b.Property<int>("DetectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("detection_count");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_spam");

                    b.Property<long?>("LastDetectedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("last_detected_date");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("training_samples");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserActionRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_at");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text")
                        .HasColumnName("issued_by");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IssuedAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("user_actions");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserRecordDto", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<long?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("email_verification_token_expires_at");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("InvitedBy")
                        .HasColumnType("character varying(450)")
                        .HasColumnName("invited_by");

                    b.Property<string>("InvitedByUserId")
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_login_at");

                    b.Property<long?>("ModifiedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<long?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("totp_enabled");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("totp_secret");

                    b.Property<long?>("TotpSetupStartedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("totp_setup_started_at");

                    b.HasKey("Id");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.VerificationTokenDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<string>("TokenTypeString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token_type");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("used_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("verification_tokens");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ChatAdminRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.ManagedChatRecordDto", "ManagedChat")
                        .WithMany("ChatAdmins")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedChat");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.DetectionResultRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.MessageRecordDto", "Message")
                        .WithMany("DetectionResults")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.InviteRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany("CreatedInvites")
                        .HasForeignKey("UserRecordDtoId");

                    b.Navigation("Creator");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.MessageEditRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.MessageRecordDto", "Message")
                        .WithMany("MessageEdits")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.RecoveryCodeRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "User")
                        .WithMany("RecoveryCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ReportDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "WebUser")
                        .WithMany("Reports")
                        .HasForeignKey("WebUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WebUser");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramLinkTokenRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany("LinkTokens")
                        .HasForeignKey("UserRecordDtoId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramUserMappingRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "User")
                        .WithMany("TelegramMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserActionRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.MessageRecordDto", "Message")
                        .WithMany("UserActions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.VerificationTokenDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "User")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ManagedChatRecordDto", b =>
                {
                    b.Navigation("ChatAdmins");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.MessageRecordDto", b =>
                {
                    b.Navigation("DetectionResults");

                    b.Navigation("MessageEdits");

                    b.Navigation("UserActions");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserRecordDto", b =>
                {
                    b.Navigation("CreatedInvites");

                    b.Navigation("LinkTokens");

                    b.Navigation("RecoveryCodes");

                    b.Navigation("Reports");

                    b.Navigation("TelegramMappings");

                    b.Navigation("VerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
