// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramGroupsAdmin.Data;

#nullable disable

namespace TgSpam_PreFilterApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017185108_DropAddedByFromUserTags")]
    partial class DropAddedByFromUserTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.AdminNoteDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorSystemIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_system_identifier");

                    b.Property<long?>("ActorTelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_telegram_user_id");

                    b.Property<string>("ActorWebUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("actor_web_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note_text");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActorTelegramUserId");

                    b.HasIndex("ActorWebUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPinned");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("admin_notes", t =>
                        {
                            t.HasCheckConstraint("CK_admin_notes_exclusive_actor", "(actor_web_user_id IS NOT NULL)::int + (actor_telegram_user_id IS NOT NULL)::int + (actor_system_identifier IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.AuditLogRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("text")
                        .HasColumnName("target_user_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ChatAdminRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCreator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_creator");

                    b.Property<DateTimeOffset>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<DateTimeOffset>("PromotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promoted_at");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("TelegramId");

                    b.ToTable("chat_admins");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ChatPromptRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("text")
                        .HasColumnName("added_by");

                    b.Property<DateTimeOffset>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<string>("CustomPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("custom_prompt");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.ToTable("chat_prompts");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ConfigRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BotProtectionConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("bot_protection_config");

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("LogConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("log_config");

                    b.Property<string>("ModerationConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("moderation_config");

                    b.Property<string>("SpamDetectionConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("spam_detection_config");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WelcomeConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("welcome_config");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("configs");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.DetectionResultRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CheckResultsJson")
                        .HasColumnType("text")
                        .HasColumnName("check_results_json");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("DetectionMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detection_method");

                    b.Property<string>("DetectionSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detection_source");

                    b.Property<int>("EditVersion")
                        .HasColumnType("integer")
                        .HasColumnName("edit_version");

                    b.Property<bool>("IsSpam")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasColumnName("is_spam")
                        .HasComputedColumnSql("(net_confidence > 0)", true);

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<int>("NetConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("net_confidence");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SystemIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("system_identifier");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<bool>("UsedForTraining")
                        .HasColumnType("boolean")
                        .HasColumnName("used_for_training");

                    b.Property<string>("WebUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("web_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("UsedForTraining");

                    b.HasIndex("WebUserId");

                    b.ToTable("detection_results", t =>
                        {
                            t.HasCheckConstraint("CK_detection_results_exclusive_actor", "(web_user_id IS NOT NULL)::int + (telegram_user_id IS NOT NULL)::int + (system_identifier IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.InviteRecordDto", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UsedBy")
                        .HasColumnType("character varying(450)")
                        .HasColumnName("used_by");

                    b.Property<string>("UserRecordDtoId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("Token");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UsedBy");

                    b.HasIndex("UserRecordDtoId");

                    b.ToTable("invites");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ManagedChatRecordDto", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatId"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("BotStatus")
                        .HasColumnType("integer")
                        .HasColumnName("bot_status");

                    b.Property<string>("ChatIconPath")
                        .HasColumnType("text")
                        .HasColumnName("chat_icon_path");

                    b.Property<string>("ChatName")
                        .HasColumnType("text")
                        .HasColumnName("chat_name");

                    b.Property<int>("ChatType")
                        .HasColumnType("integer")
                        .HasColumnName("chat_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("settings_json");

                    b.HasKey("ChatId");

                    b.ToTable("managed_chats");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.MessageEditRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("EditDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edit_date");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("NewContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("new_content_hash");

                    b.Property<string>("NewText")
                        .HasColumnType("text")
                        .HasColumnName("new_text");

                    b.Property<string>("OldContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("old_content_hash");

                    b.Property<string>("OldText")
                        .HasColumnType("text")
                        .HasColumnName("old_text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("message_edits");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.MessageRecordDto", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletionSource")
                        .HasColumnType("text")
                        .HasColumnName("deletion_source");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edit_date");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("PhotoFileId")
                        .HasColumnType("text")
                        .HasColumnName("photo_file_id");

                    b.Property<int?>("PhotoFileSize")
                        .HasColumnType("integer")
                        .HasColumnName("photo_file_size");

                    b.Property<string>("PhotoLocalPath")
                        .HasColumnType("text")
                        .HasColumnName("photo_local_path");

                    b.Property<string>("PhotoThumbnailPath")
                        .HasColumnType("text")
                        .HasColumnName("photo_thumbnail_path");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_message_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Urls")
                        .HasColumnType("text")
                        .HasColumnName("urls");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.RecoveryCodeRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("recovery_codes");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ReportDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionTaken")
                        .HasColumnType("text")
                        .HasColumnName("action_taken");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text")
                        .HasColumnName("admin_notes");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<int?>("ReportCommandMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("report_command_message_id");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<long?>("ReportedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("ReportedByUserName")
                        .HasColumnType("text")
                        .HasColumnName("reported_by_user_name");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WebUserId")
                        .HasColumnType("character varying(450)")
                        .HasColumnName("web_user_id");

                    b.HasKey("Id");

                    b.HasIndex("WebUserId");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.SpamCheckConfigRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<string>("CheckName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("check_name");

                    b.Property<int?>("ConfidenceThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_threshold");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text")
                        .HasColumnName("configuration_json");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.HasKey("Id");

                    b.ToTable("spam_check_configs");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.SpamDetectionConfigRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChatId")
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("spam_detection_configs");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.StopWordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("SystemIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("system_identifier");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<string>("WebUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("web_user_id");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("WebUserId");

                    b.ToTable("stop_words", t =>
                        {
                            t.HasCheckConstraint("CK_stop_words_exclusive_actor", "(web_user_id IS NOT NULL)::int + (telegram_user_id IS NOT NULL)::int + (system_identifier IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TagDefinitionDto", b =>
                {
                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag_name");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.HasKey("TagName");

                    b.HasIndex("UsageCount");

                    b.ToTable("tag_definitions");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramLinkTokenRecordDto", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<long?>("UsedByTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("used_by_telegram_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserRecordDtoId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.HasIndex("UserRecordDtoId");

                    b.ToTable("telegram_link_tokens");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramUserDto", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PhotoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("photo_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserPhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_photo_path");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("TelegramUserId");

                    b.HasIndex("IsTrusted");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("Username");

                    b.ToTable("telegram_users");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramUserMappingRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("text")
                        .HasColumnName("telegram_username");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("telegram_user_mappings");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserActionRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SystemIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("system_identifier");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("WebUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("web_user_id");

                    b.HasKey("Id");

                    b.HasIndex("IssuedAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("WebUserId");

                    b.ToTable("user_actions", t =>
                        {
                            t.HasCheckConstraint("CK_user_actions_exclusive_actor", "(web_user_id IS NOT NULL)::int + (telegram_user_id IS NOT NULL)::int + (system_identifier IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserRecordDto", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTimeOffset?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_expires_at");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("InvitedBy")
                        .HasColumnType("character varying(450)")
                        .HasColumnName("invited_by");

                    b.Property<string>("InvitedByUserId")
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("totp_enabled");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("totp_secret");

                    b.Property<DateTimeOffset?>("TotpSetupStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_setup_started_at");

                    b.HasKey("Id");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserTagDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorSystemIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_system_identifier");

                    b.Property<long?>("ActorTelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_telegram_user_id");

                    b.Property<string>("ActorWebUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("actor_web_user_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int?>("ConfidenceModifier")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_modifier");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("RemovedBySystemIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("removed_by_system_identifier");

                    b.Property<long?>("RemovedByTelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("removed_by_telegram_user_id");

                    b.Property<string>("RemovedByWebUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("removed_by_web_user_id");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag_name");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorTelegramUserId");

                    b.HasIndex("ActorWebUserId");

                    b.HasIndex("RemovedAt");

                    b.HasIndex("TagName");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("user_tags", t =>
                        {
                            t.HasCheckConstraint("CK_user_tags_exclusive_actor", "(actor_web_user_id IS NOT NULL)::int + (actor_telegram_user_id IS NOT NULL)::int + (actor_system_identifier IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.VerificationTokenDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<string>("TokenTypeString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token_type");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("verification_tokens");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.WelcomeResponseDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DmFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("dm_fallback");

                    b.Property<bool>("DmSent")
                        .HasColumnType("boolean")
                        .HasColumnName("dm_sent");

                    b.Property<DateTimeOffset>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("response");

                    b.Property<Guid?>("TimeoutJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("timeout_job_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<int>("WelcomeMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("welcome_message_id");

                    b.HasKey("Id");

                    b.ToTable("welcome_responses");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Expression")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Expression")
                        .HasDatabaseName("IX_CronTickers_Expression");

                    b.ToTable("CronTickers", "ticker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerOccurrenceEntity<TickerQ.EntityFrameworkCore.Entities.CronTickerEntity>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CronTickerId")
                        .HasColumnType("uuid");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockHolder")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CronTickerId")
                        .HasDatabaseName("IX_CronTickerOccurrence_CronTickerId");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_ExecutionTime");

                    b.HasIndex("CronTickerId", "ExecutionTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_CronTickerId_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_Status_ExecutionTime");

                    b.ToTable("CronTickerOccurrences", "ticker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchParent")
                        .HasColumnType("uuid");

                    b.Property<int?>("BatchRunCondition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("LockHolder")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchParent");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_Status_ExecutionTime");

                    b.ToTable("TimeTickers", "ticker");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.AdminNoteDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.TelegramUserDto", null)
                        .WithMany()
                        .HasForeignKey("ActorTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany()
                        .HasForeignKey("ActorWebUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.TelegramUserDto", "TelegramUser")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ChatAdminRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.ManagedChatRecordDto", "ManagedChat")
                        .WithMany("ChatAdmins")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedChat");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.DetectionResultRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.MessageRecordDto", "Message")
                        .WithMany("DetectionResults")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramGroupsAdmin.Data.Models.TelegramUserDto", null)
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany()
                        .HasForeignKey("WebUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.InviteRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany("CreatedInvites")
                        .HasForeignKey("UserRecordDtoId");

                    b.Navigation("Creator");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.MessageEditRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.MessageRecordDto", "Message")
                        .WithMany("MessageEdits")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.RecoveryCodeRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "User")
                        .WithMany("RecoveryCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ReportDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "WebUser")
                        .WithMany("Reports")
                        .HasForeignKey("WebUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WebUser");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.StopWordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.TelegramUserDto", null)
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany()
                        .HasForeignKey("WebUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramLinkTokenRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany("LinkTokens")
                        .HasForeignKey("UserRecordDtoId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.TelegramUserMappingRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "User")
                        .WithMany("TelegramMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserActionRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.MessageRecordDto", "Message")
                        .WithMany("UserActions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.TelegramUserDto", null)
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany()
                        .HasForeignKey("WebUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserRecordDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserTagDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.TelegramUserDto", null)
                        .WithMany()
                        .HasForeignKey("ActorTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", null)
                        .WithMany()
                        .HasForeignKey("ActorWebUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelegramGroupsAdmin.Data.Models.TelegramUserDto", "TelegramUser")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.VerificationTokenDto", b =>
                {
                    b.HasOne("TelegramGroupsAdmin.Data.Models.UserRecordDto", "User")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerOccurrenceEntity<TickerQ.EntityFrameworkCore.Entities.CronTickerEntity>", b =>
                {
                    b.HasOne("TickerQ.EntityFrameworkCore.Entities.CronTickerEntity", "CronTicker")
                        .WithMany()
                        .HasForeignKey("CronTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CronTicker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.HasOne("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", "ParentJob")
                        .WithMany("ChildJobs")
                        .HasForeignKey("BatchParent")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.ManagedChatRecordDto", b =>
                {
                    b.Navigation("ChatAdmins");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.MessageRecordDto", b =>
                {
                    b.Navigation("DetectionResults");

                    b.Navigation("MessageEdits");

                    b.Navigation("UserActions");
                });

            modelBuilder.Entity("TelegramGroupsAdmin.Data.Models.UserRecordDto", b =>
                {
                    b.Navigation("CreatedInvites");

                    b.Navigation("LinkTokens");

                    b.Navigation("RecoveryCodes");

                    b.Navigation("Reports");

                    b.Navigation("TelegramMappings");

                    b.Navigation("VerificationTokens");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.Navigation("ChildJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
